CREATE TABLE IF NOT EXISTS usuario (
	IDUSUARIO INT(11) NOT NULL,
	NMUSUARIO VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	SGUSUARIO VARCHAR(25) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	FLATIVO VARCHAR(1) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	IDUSUARIOINC INT(11) NOT NULL DEFAULT '0',
	DTINCLUSAO DATETIME NOT NULL,
	IDUSUARIOALT INT(11) NOT NULL DEFAULT '0',
	DTALTERACAO DATETIME NOT NULL,
	PWUSUARIO VARCHAR(32) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (IDUSUARIO) USING BTREE,
	UNIQUE INDEX SGUSUARIO (SGUSUARIO) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;