CREATE TABLE IF NOT EXISTS perfil (
  IDPERFIL int(11) NOT NULL,
  NMPERFIL varchar(100) NOT NULL,
  IDUSUARIOINC int(11) DEFAULT NULL,
  DTINCLUSAO datetime DEFAULT NULL,
  IDUSUARIOALT int(11) DEFAULT NULL,
  DTALTERACAO datetime DEFAULT NULL,
PRIMARY KEY (IDPERFIL) USING BTREE
)
COLLATE='utf8_general_ci' 
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS vigilante (
	IDVIGILANTE INT(11) NOT NULL,
	NMVIGILANTE VARCHAR(50) NOT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
  	DTINCLUSAO datetime DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
  	DTALTERACAO datetime DEFAULT NULL,
	PRIMARY KEY (IDVIGILANTE) USING BTREE
) 
COLLATE='utf8_general_ci' 
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tipoocorrencia (
	IDTIPOOCORRENCIA INT(11) NOT NULL,
	NMOCORRENCIA VARCHAR(50) NOT NULL,
	FLAREAABERTA VARCHAR(1) NOT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
  	DTINCLUSAO datetime DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
  	DTALTERACAO datetime DEFAULT NULL,
	PRIMARY KEY (IDTIPOOCORRENCIA) USING BTREE
) 
COLLATE='utf8_general_ci' 
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS area (
	IDAREA INT(11) NOT NULL,
	NMAREA VARCHAR(50) NOT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
  	DTINCLUSAO datetime DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
  	DTALTERACAO datetime DEFAULT NULL,
	PRIMARY KEY (IDAREA) USING BTREE
) 
COLLATE='utf8_general_ci' 
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS posto (
	IDPOSTO INT(11) NOT NULL,
	NMPOSTO VARCHAR(50) NOT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
  	DTINCLUSAO datetime DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
  	DTALTERACAO datetime DEFAULT NULL,
	PRIMARY KEY (IDPOSTO) USING BTREE
) 
COLLATE='utf8_general_ci' 
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS usuario (
	IDUSUARIO INT(11) NOT NULL,
	NMUSUARIO VARCHAR(50) NOT NULL DEFAULT '',
	SGUSUARIO VARCHAR(25) NOT NULL DEFAULT '',
	PWUSUARIO VARCHAR(32) NOT NULL DEFAULT '',
	IDPERFIL INT(11) NULL DEFAULT NULL,
	FLATIVO VARCHAR(1) NOT NULL DEFAULT '',
	IDUSUARIOINC INT(11) NOT NULL DEFAULT '0',
	DTINCLUSAO DATETIME NOT NULL,
	IDUSUARIOALT INT(11) NOT NULL DEFAULT '0',
	DTALTERACAO DATETIME NOT NULL,
	PRIMARY KEY (IDUSUARIO) USING BTREE,
	UNIQUE INDEX SGUSUARIO (SGUSUARIO) USING BTREE,
	CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY (IDPERFIL) REFERENCES perfil (IDPERFIL)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

INSERT IGNORE INTO usuario (IDUSUARIO,NMUSUARIO, SGUSUARIO, PWUSUARIO, IDPERFIL, FLATIVO, IDUSUARIOINC,DTINCLUSAO,IDUSUARIOALT,DTALTERACAO)
	VALUES (1, 'Adminstrador do Sistema', 'admin', '0192023a7bbd73250516f069df18b500', NULL, 'S', 1, '2020-05-10 20:11:33', 1, '2020-05-12 23:33:37');

CREATE TABLE IF NOT EXISTS postoarea (
	IDPOSTOAREA INT(11) NOT NULL,
	IDPOSTO	INT(11) NOT NULL,
	IDAREA 	INT(11) NOT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
  	DTINCLUSAO datetime DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
  	DTALTERACAO datetime DEFAULT NULL,
	PRIMARY KEY (IDPOSTOAREA) USING BTREE,
	CONSTRAINT FK_POSTOAREA_POSTO FOREIGN KEY (IDPOSTO) REFERENCES posto (IDPOSTO),
	CONSTRAINT FK_POSTOAREA_AREA FOREIGN KEY (IDAREA) REFERENCES area (IDAREA)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ocorrencia (
	IDOCORRENCIA INT(11) NOT NULL,
	IDTIPOOCORRENCIA INT(11) NOT NULL,
	IDVIGILANTE INT(11) NOT NULL,
	IDPOSTOAREA INT(11) NOT NULL,
	DTOCORRENCIA DATETIME NOT NULL,
	DSOCORRENCIA LONGTEXT NOT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
  	DTINCLUSAO DATETIME DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
  	DTALTERACAO DATETIME DEFAULT NULL,
	PRIMARY KEY (IDOCORRENCIA) USING BTREE,
	CONSTRAINT FK_OCORRENCIA_TIPOOCORRENCIA FOREIGN KEY (IDTIPOOCORRENCIA) REFERENCES tipoocorrencia (IDTIPOOCORRENCIA),
	CONSTRAINT FK_OCORRENCIA_VIGILANTE FOREIGN KEY (IDVIGILANTE) REFERENCES vigilante (IDVIGILANTE),
	CONSTRAINT FK_OCORRENCIA_POSTOAREA FOREIGN KEY (IDPOSTOAREA) REFERENCES postoarea (IDPOSTOAREA)
)
COLLATE='utf8_general_ci' 
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS permissao (
	IDPERMISSAO INT(11) NOT NULL,
	NMPERMISSAO VARCHAR(25) NOT NULL,
	SGPERMISSAO VARCHAR(25) NOT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
  	DTINCLUSAO DATETIME DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
  	DTALTERACAO DATETIME DEFAULT NULL,
	PRIMARY KEY (IDPERMISSAO) USING BTREE,
)
COLLATE='utf8_general_ci' 
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS perfilpermissao (
	IDPERFILPERMISSAO INT(11) NOT NULL,
	IDPERFIL INT(11) NOT NULL,
	IDPERMISSAO INT(11) NOT NULL,
	FLCONSULTA VARCHAR(1) NOT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
  	DTINCLUSAO DATETIME DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
  	DTALTERACAO DATETIME DEFAULT NULL,
	PRIMARY KEY (IDPERFILPERMISSAO) USING BTREE,
	CONSTRAINT FK_PERFILPERMISSAO_PERFIL FOREIGN KEY (IDPERFIL) REFERENCES perfil (IDPERFIL),
	CONSTRAINT FK_PERFILPERMISSAO_PERMISSAO FOREIGN KEY (IDPERMISSAO) REFERENCES permissao (IDPERMISSAO)
)
COLLATE='utf8_general_ci' 
ENGINE=InnoDB;

INSERT IGNORE INTO permissao (IDPERMISSAO,NMPERMISSAO,SGPERMISSAO,IDUSUARIOINC,DTINCLUSAO,IDUSUARIOALT,DTALTERACAO) 
	VALUES  (1,'Cadastro Perfil','CAD_PERFIL',0,CURRENT_TIMESTAMP(),0,CURRENT_TIMESTAMP()),
	        (2,'Cadastro Vigilante','CAD_VIGILANTE',0,CURRENT_TIMESTAMP(),0,CURRENT_TIMESTAMP()),
			(3,'Cadastro Usuário','CAD_USUARIO',0,CURRENT_TIMESTAMP(),0,CURRENT_TIMESTAMP()),
			(4,'Cadastro Tipo Ocorrência','CAD_TIPOOCORRENCIA',0,CURRENT_TIMESTAMP(),0,CURRENT_TIMESTAMP()),
			(5,'Cadastro Posto Área','CAD_POSTOAREA',0,CURRENT_TIMESTAMP(),0,CURRENT_TIMESTAMP()),
			(6,'Cadastro Posto','CAD_POSTO',0,CURRENT_TIMESTAMP(),0,CURRENT_TIMESTAMP()),
			(7,'Cadastro Posto','CAD_OCORRENCIA',0,CURRENT_TIMESTAMP(),0,CURRENT_TIMESTAMP()),
			(8,'Relaório Gerencial','REL_RELATORIO',0,CURRENT_TIMESTAMP(),0,CURRENT_TIMESTAMP());

			
CREATE TABLE IF NOT EXISTS campus (
	IDCAMPUS INT(11) NOT NULL,
	NMCAMPUS varchar(100) NOT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
	DTINCLUSAO datetime DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
	DTALTERACAO datetime DEFAULT NULL,
	PRIMARY KEY (IDCAMPUS) USING BTREE
)
COLLATE='utf8_general_ci' 
ENGINE=InnoDB;

ALTER TABLE usuario
	ADD COLUMN IDCAMPUS INT(11) NOT NULL AFTER DTALTERACAO,
	ADD CONSTRAINT FK_USUARIO_CAMPUS FOREIGN KEY (IDCAMPUS) REFERENCES campus (IDCAMPUS);

ALTER TABLE postoarea
	ADD COLUMN IDCAMPUS INT(11) NOT NULL AFTER DTALTERACAO,
	ADD CONSTRAINT FK_POSTOAREA_CAMPUS FOREIGN KEY (IDCAMPUS) REFERENCES campus (IDCAMPUS);

CREATE TABLE IF NOT EXISTS ocorrenciaanexo (
	IDOCORRENCIAANEXO int(11) NOT NULL,
	IDOCORRENCIA int(11) NOT NULL,
	DSARQUIVO longblob DEFAULT NULL,
	NRTAMANHOARQUIVO int(11) DEFAULT NULL,
	NMARQUIVO VARCHAR(30) DEFAULT NULL,
	TPANEXO datetime DEFAULT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
	DTINCLUSAO datetime DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
	DTALTERACAO datetime DEFAULT NULL,
	PRIMARY KEY (IDOCORRENCIAANEXO) USING BTREE
)
COLLATE='utf8_general_ci' 
ENGINE=InnoDB;

ALTER TABLE ocorrenciaanexo
	ADD CONSTRAINT FK_OCORRENCIAANEXO_OCORRENCIA FOREIGN KEY (IDOCORRENCIA) REFERENCES ocorrencia (IDOCORRENCIA) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS grupo (
	IDGRUPO int(11) NOT NULL,
	NMGRUPO varchar(100) NOT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
	DTINCLUSAO datetime DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
	DTALTERACAO datetime DEFAULT NULL,
	PRIMARY KEY (IDGRUPO) USING BTREE
)
COLLATE='utf8_general_ci' 
ENGINE=INNODB;

ALTER TABLE area
	ADD COLUMN IDGRUPO INT(11) NOT NULL AFTER DTALTERACAO,
	ADD CONSTRAINT FK_AREA_GRUPO FOREIGN KEY (IDGRUPO) REFERENCES grupo (IDGRUPO);

ALTER TABLE ocorrenciaanexo
	CHANGE COLUMN TPANEXO TPANEXO VARCHAR(25) NULL DEFAULT NULL AFTER NMARQUIVO;

INSERT IGNORE INTO permissao (IDPERMISSAO,NMPERMISSAO,SGPERMISSAO,IDUSUARIOINC,DTINCLUSAO,IDUSUARIOALT,DTALTERACAO) 
	VALUES  (9,'Cadastro Áreas','CAD_AREA',0,CURRENT_TIMESTAMP(),0,CURRENT_TIMESTAMP()),
	        (10,'Cadastro Grupos','CAD_GRUPO',0,CURRENT_TIMESTAMP(),0,CURRENT_TIMESTAMP(),
			(11, 'Manutenção de Ocorrências', 'TAR_MANUTENCAO', 0, CURRENT_TIMESTAMP(), 0, CURRENT_TIMESTAMP()));

alter table ocorrencia add column TPSTATUS VARCHAR(1) null default 'E' after DTOCORRENCIA

CREATE TABLE IF NOT EXISTS manutencao (
	IDMANUTENCAO INT(11) NOT NULL,
	IDOCORRENCIA INT(11) NOT NULL,
	DSPARECER LONGTEXT NULL DEFAULT NULL,
	IDUSUARIOINC int(11) DEFAULT NULL,
	DTINCLUSAO datetime DEFAULT NULL,
	IDUSUARIOALT int(11) DEFAULT NULL,
	DTALTERACAO datetime DEFAULT NULL,
	PRIMARY KEY (IDMANUTENCAO) USING BTREE
)
COLLATE='utf8_general_ci' 
ENGINE=INNODB;

ALTER TABLE manutencao
	ADD CONSTRAINT FK_MANUTENCAO_OCORRENCIA FOREIGN KEY (IDOCORRENCIA) REFERENCES ocorrencia (IDOCORRENCIA) ON DELETE CASCADE;

alter table usuario add column FLPRIMEIROACESSO VARCHAR(1) null default 'S';